name: Semantic Versioning 

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Automatic Semantic Versioning
        uses: bitshifted/git-auto-semver@v1.1.0          

